### ISSUE TITLE
I'm getting KeyError from Python 

### ISSUE THREAD

**Issue by marcelo-change** [Nadock/verified_commits_check#8]
I create a new pipeline using the configuration below:

```
name: Run verified commits check

on: pull_request

jobs:
  verified_commit_check:
    name: Check for unverified commits
    runs-on: ubuntu-latest
    steps:
      - uses: nadock/verified_commits_check@v1.1.0
```

When I run that Pipeline I'm getting the error below:

```
Set up job
   Current runner version: '2.277.1'
   Operating System
   Virtual Environment
   GITHUB_TOKEN Permissions
   Prepare workflow directory
   Prepare all required actions
   Getting action download info
   Download action repository 'nadock/verified_commits_check@v1.1.0'

Build nadock/verified_commits_check@v1.1.0
   Build container for action use: '/home/runner/work/_actions/nadock/verified_commits_check/v1.1.0/Dockerfile'.

Run nadock/verified_commits_check@v1.1.0
   Run nadock/verified_commits_check@v1.1.0
   /usr/bin/docker run --name e43f21342fee364082a9644e37b18d9653_2131f4 --label 5588e4 --workdir 
   /github/workspace --rm -e GITHUB_TOKEN -e INPUT_GITHUB_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e 
   GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e 
   GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e 
   GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e 
   GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e 
   GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e 
   RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e 
   ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v 
   "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v 
   "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v 
   "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/infrastructure-as- 
  code/infrastructure-as-code":"/github/workspace" 5588e4:3f21342fee364082a9644e37b18d9653
   + cd /opt/action
   + python3 -m src.action
   Traceback (most recent call last):
     File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
       return _run_code(code, main_globals, None,
     File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
       exec(code, run_globals)
     File "/opt/action/src/action.py", line 132, in <module>
       sys.exit(main())
     File "/opt/action/src/action.py", line 31, in main
       commit_hashes = get_commits_from_event(event)
     File "/opt/action/src/action.py", line 112, in get_commits_from_event
       return [commit["id"] for commit in event["commits"]]
   KeyError: 'commits'

Complete job
Cleaning up orphan processes
```

**Comment by Nadock** [comment]
Hi @marcelo-change, I think the issue you're seeing is because you're running this `on: pull_request`. Currently this action only supports `on: push`.

The `README.md` could be more clear about this and also the error message should be more specific — something I can do when I have a spare few minutes. (Happy for you to also open a PR too)

However, I was also wondering what you were attempting to achieve with this configuration? What does the branch protection rule not offer that you were looking for? Sounds like there might be an opportunity for a new feature here.
